# Required properties
sonar.projectKey=EventManagement
sonar.projectName=Event Management
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
# or specify specific directories like:
# sonar.sources=src,force-app

# Exclusions (optional)
sonar.exclusions=**/*.min.js,node_modules/**,coverage/**,dist/**,build/**

# Language-specific settings (if needed)
# For Apex/Salesforce projects:
# sonar.apex.coverage.reportPath=test-result-codecoverage.json

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server URL (if not using default localhost)
sonar.host.url=http://localhost:9000
# Auth token
sonar.token=sqa_d0b8330d645751a5c2fe551aa9d598e63c715fa4



#  First Start the C:\sonarqube\bin\windows-x86-64\StartSonar.exe batch file to access http://localhost:9000/